LINES = [# line 1
    [
        ('XinZhuang',3),
        ('WaiHuanLu',2),
        ('LianHuaLu',3),
        ('JinJiangLeYuan',3),
        ('ShangHaiNanZhan',3),
        ('CaoBaoLu',3),
        ('ShangHaiTiYuGuan',2),
        ('XuJiaHui',2),
        ('HengShanLu',2),
        ('ChangShuLu',2),
        ('ShanXiNanLu',2),
        ('HuangPiNanLu',3),
        ('RenMinGuangChang',2),
        ('XinZhaLu',2),
        ('HanZhongLu',3),
        ('ShangHaiHuoCheZhan',2),
        ('ZhongShanBeiLu',3),
        ('YanChangLu',2),
        ('ShangHaiMaXiCheng',2),
        ('WenShuiLu',3),
        ('PengPuXinChun',3),
        ('GongKangLu',2),
        ('TongHeXinChun',2),
        ('HuLanLu',3),
        ('GongFuXinChun',3),
        ('BaoAnGongLu',2),
        ('YouYiXiLu',3),
        ('FuJinLu',0)
    ], # line 2
    [
        ('XuJingDong',4),
        ('HongQiaoHuoCheZhan',2),
        ('HongQiaoErHaoHangZhanLou',7),
        ('SongHongLu',2),
        ('BeiXinJing',2),
        ('WeiNingLu',3),
        ('LouShanGuanLu',3),
        ('ZhongShanGongYuan',2),
        ('JiangSuLu',3),
        ('JingAnSi',2),
        ('NanJingXiLu',3),
        ('RenMinGuangChang',2),
        ('NanJingDongLu',3),
        ('LuJiaZui',2),
        ('DongChangLu',2),
        ('ShiJiDadao',3),
        ('ShangHaiKeJiGuan',2),
        ('ShiJiGongYuan',2),
        ('LongYangLu',4),
        ('ZhangJiangGaoKe',3),
        ('JinKeLu',3),
        ('GuangLanLu',5),
        ('TangZhen',4),
        ('ChuangXinZhongLu',3),
        ('HuaXiaDongLu',4),
        ('ChuanSha',4),
        ('LingKongLu',5),
        ('YuanDongDaDao',7),
        ('HaiTianSanLu',3),
        ('PuDongGuoJiJiChang',0)
    ], # line 3
    [
        ('ShanHaiNanZhan',3),
        ('ShiLongLu',3),
        ('LongCaoLu',2),
        ('YiShanLu',2),
        ('HongQiaoLu',3),
        ('YanAnXiLu',2),
        ('ZhongShanGongYuan',2),
        ('JinShaJiangLu',2),
        ('CaoYangLu',3),
        ('ZhenPingLu',2),
        ('ZhongTanLu',3),
        ('ShangHaiHuoCheZhan',3),
        ('BaoShanLu',2),
        ('DongBaoXingLu',3),
        ('HongKouZuQiuChang',2),
        ('ChiFengLu',2),
        ('DaBaiShu',3),
        ('JiangWanZhen',2),
        ('YinGaoXiLu',3),
        ('ChangJiangNanLu',2),
        ('SongFaLu',3),
        ('ZhangHuaBang',2),
        ('SongBinLu',2),
        ('ShuiChanLu',3),
        ('BaoYangLu',2),
        ('YouYiLu',2),
        ('TieLiLu',4),
        ('JiangYangBeiLu',0)
    ], # line 4
    [
        ('ShangHaiTiYuGuan', 3),
        ('YiShanLu', 3),
        ('HongQiaoLu', 2),
        ('YanAnXiLu', 2),
        ('ZhongShanGongYuan', 3),
        ('JinShaJiangLu', 2),
        ('CaoYangLu', 2),
        ('ZhenPingLu', 2),
        ('ZhongTanLu', 3),
        ('ShangHaiHuoCheZhan', 4),
        ('BaoShanLu', 2),
        ('HaiLunLu', 2),
        ('LinPingLu', 3),
        ('DaLianLu', 1),
        ('YangShuPuLu',3),
        ('PuDongDaDao',2),
        ('ShiJiDadao', 2),
        ('PuDianLu',2),
        ('LanChunLu',2),
        ('TangQiao',3),
        ('NanPuDaQiao',2),
        ('XiZangNanLu',3),
        ('LuBanLu',2),
        ('DaMuQiaoLu',2),
        ('DongAnLu',3),
        ('ShanghaiTiYuChang',2),
        ('ShangHaiTiYuGuan',0)
    ], ]# line 5
#     [
#         ('XinZhuang',3),
#         ('ChunShenLu',2),
#         ('YinDuLu',4),
#         ('XuQiao',3),
#         ('BeiQiao',3),
#         ('JianChuanLu',2),
#         ('DongChuanLu',3),
#         ('JinPingLu',2),
#         ('HuaNingLu',3),
#         ('WenJingLu',3),
#         ('MinHangKaiFaQu',0)
#     ], # line 6
#     [
#         ('DongFangTiYuZhongXin',3),
#         ('LingYanNanLu',2),
#         ('ShangNanLu',2),
#         ('HuaXiaXiLu',3),
#         ('GaoQingLu',2),
#         ('DongMingLu',3),
#         ('GaoKeXiLu',2),
#         ('LinYiXinChun',3),
#         ('ShangHaiErTongYiXueZhongXin',1),
#         ('LanChunLu',3),
#         ('PuDianLu',3),
#         ('ShiJiDadao',2),
#         ('YuanShenTiYuZhongXin',2),
#         ('MinShengLu',2),
#         ('BeiYangTingLu',3),
#         ('DePingLu',2),
#         ('YunShanLu',2),
#         ('JinQiaoLu',3),
#         ('BoXingLu',2),
#         ('WuLianLu',2),
#         ('JuFengLu',3),
#         ('DongJingLu',2),
#         ('WuZhouDaDao',2),
#         ('ZhouHaiLu',3),
#         ('WaiGaoQiaoBaoShuiQuNanZhan',3),
#         ('HangJinLu',2),
#         ('WaiGaoQiaoBaoShuiQuBeiZhan',4),
#         ('GangChengLu',0)
#     ], # line 7
#     lin7 = [
#         ('MeiLanHu',3),
#         ('LuoNanXinChun',4),
#         ('PanGuangLu',2),
#         ('LiuHang',3),
#         ('GuChunGongYuan',3),
#         ('QiHuaLu',3),
#         ('ShangHaiDaXue',2),
#         ('NanChenLu',3),
#         ('ShangDaLu',2),
#         ('ChangZhongLu',2),
#         ('DaChangLu',2),
#         ('XingZhiLu',3),
#         ('DaHuaSanLu',2),
#         ('XinChunLu',2),
#         ('LangGaoLu',3),
#         ('ZhenPingLu',3),
#         ('ChangShouLu',2),
#         ('ChangPingLu',2),
#         ('JingAnSi',3),
#         ('ChangShuLu',2),
#         ('ZhaoJiaBangLu',3),
#         ('DongAnLu',2),
#         ('LongHuaZhongLu',3),
#         ('HouTan',3),
#         ('ChangQingLu',2),
#         ('YaoHuaLu',1),
#         ('YunTaiLu',3),
#         ('GaoKeXiLu',2),
#         ('YangGaoNanLu',3),
#         ('JinXiuLu',2),
#         ('FangHuaLu',4),
#         ('LongYangLu',3),
#         ('HuaMuLu',0)
#     ], # line 8
#     [
#         ('ShenSheGongLu',3),
#         ('LianHangLu',2),
#         ('JiangYueLu',2),
#         ('PuJiangLu',3),
#         ('LuHengLu',4),
#         ('LingZhaoXinChun',3),
#         ('DongFangTiYuZhongXin',2),
#         ('YangSi',2),
#         ('ChengShanLu',2),
#         ('YaoHuaLu',2),
#         ('ZhongHuaYiShuGong',3),
#         ('XiZangNanLu',2),
#         ('LuJiaBangLu',2),
#         ('LaoXiMen',2),
#         ('DaShiJie',2),
#         ('RenMinGuangChang',2),
#         ('QuFuLu',2),
#         ('ZhongXingLu',2),
#         ('XiZangBeiLu',2),
#         ('HongKouZuQiuChang',3),
#         ('QuYangLu',2),
#         ('SiPingLu',2),
#         ('AnShanXinChun',2),
#         ('JiangPuLu',2),
#         ('HuangXingLu',2),
#         ('YanJiZhongLu',2),
#         ('YinXiangLu',2),
#         ('NenJiangLu',2),
#         ('ShiGuangLu',2)
#     ], # line 9
#     [
#         ('SongJiangNanZhan',3),
#         ('ZuiBaiChi',2),
#         ('SongJiangTiYuZhongXin',2),
#         ('SongJiangXinCheng',3),
#         ('SongJiangDaXueCheng',4),
#         ('DongTing',3),
#         ('SheShan',4),
#         ('SiTing',6),
#         ('JiuTing',3),
#         ('ZhongChunLu',2),
#         ('QiBao',2),
#         ('XingZhongLu',3),
#         ('HeChuangLu',1),
#         ('CaoHeTingKaiFaQu',3),
#         ('GuiLinLu',2),
#         ('YiShanLu',2),
#         ('XuJiaHui',2),
#         ('ZhaoJiaBangLu',2),
#         ('JiaShanLu',1),
#         ('DaPuQiao',2),
#         ('MaDangLu',1),
#         ('LuJiaBangLu',2),
#         ('XiaoNanMen',3),
#         ('ShangChengLu',2),
#         ('ShiJiDadao',3),
#         ('YangGaoZhongLu',0)
#     ], # line 10
#     [
#         ('HangZhongLu',4),
#         ('ZiTengLu',2),
#         ('LongBaiXinChun',4),
#         ('LongXiLu',3),
#         ('ShuiChengLu',2),
#         ('YiLiLu',2),
#         ('SongYuanLu',3),
#         ('HonhQiaoLu',2),
#         ('JiangTongDaXue',2),
#         ('ShangHaiTuShuGuan',3),
#         ('ShanXiNanLu',3),
#         ('XinTianDi',2),
#         ('LaoXiMen',3),
#         ('YuYuan',2),
#         ('NanJingDongLu',2),
#         ('TianTongLu',3),
#         ('SiChuanBeiLu',2),
#         ('HaiLunLu',2),
#         ('YouDianXinChun',3),
#         ('SiPingLu',2),
#         ('TongJiDaXue',2),
#         ('GuoQuanLu',2),
#         ('WuJiaoChang',2),
#         ('JiangWanTiYuChang',2),
#         ('SanMenLu',2),
#         ('YinGaoDongLu',2),
#         ('XinJiangWanCheng',0)
#     ], # line 11
#     [
#         ('HuaQiao', 3),
#         ('GuangMingLu', 4),
#         ('ZhaoFengLu', 3),
#         ('AnTing', 3),
#         ('ShangHaiQiCheCheng', 3),
#         ('ChangJiDongLu', 5),
#         ('ShangHaiSaiCheChang', 4),
#         ('JiaDingXinCheng', 4),
#         ('MaLu', 6),
#         ('NanXiang', 4),
#         ('TaoPuXinCun', 2),
#         ('WuWeiLu', 3),
#         ('QiLianShanLu', 2),
#         ('LiZiYuan', 3),
#         ('ShangHaiXiZhan', 3),
#         ('ZhenRu', 2),
#         ('FengQiaoLu', 2),
#         ('CaoYangLu', 2),
#         ('LongDeLu', 3),
#         ('JiangSuLu', 4),
#         ('JiaoTongDaXue', 2),
#         ('XuJiaHui', 3),
#         ('ShangHaiYouYongGuan', 3),
#         ('LongHua', 2),
#         ('YunJinLu', 2),
#         ('LongYaoLu', 4),
#         ('DongFangTiYuZhongXin', 4),
#         ('SanLin', 2),
#         ('SanLinDong', 3),
#         ('PuSanLu', 2),
#         ('YanYuLu', 2),
#         ('YuQiao', 4),
#         ('LuoShanLu', 3),
#         ('XiuYanLu', 3),
#         ('KangXinGongLu', 0)
#     ], # line 12
#     [
#         ('QiZiLu', 3),
#         ('HongZiLu', 3),
#         ('GuDaiLu', 3),
#         ('DongLanLu', 3),
#         ('HongMeiLu', 2),
#         ('HongCaoLu', 2),
#         ('GuiLinGongYuan', 3),
#         ('CaoBaoLu', 2),
#         ('LongCaoLu', 3),
#         ('LongHua', 3),
#         ('LongHuaZhongLu', 3),
#         ('DaMuQiaoLu', 2),
#         ('JiaShanLu', 3),
#         ('ShanXiNanLu', 3),
#         ('NanJingXiLu', 3),
#         ('HanZhongLu', 3),
#         ('QuFuLu', 2),
#         ('TianTongLu', 3),
#         ('GuoJiKeYunZhongXin', 3),
#         ('TiLanQiao', 2),
#         ('DaLianLu', 2),
#         ('JiangPuGongYuan', 3),
#         ('NingGuoLu', 2),
#         ('LongChangLu', 2),
#         ('AiGuoLu', 2),
#         ('FuXingDao', 3),
#         ('DongLuLu', 3),
#         ('JuFengLu', 3),
#         ('YangGaoBeiLu', 2),
#         ('JinJingLu', 2),
#         ('ShenJiangLu', 5),
#         ('JinHaiLu', 0)
#     ], # line 13
#     [
#         ('JinYunLu', 3),
#         ('JinShaJiangXiLu', 4),
#         ('FengZhuang', 2),
#         ('QiLianShanNanLu', 3),
#         ('ZhenBeiLu', 2),
#         ('DaDuHeLu', 3),
#         ('JinShaJiangLu', 3),
#         ('LongDeLu', 2),
#         ('WuNingLu', 3),
#         ('ChangShouLu', 2),
#         ('JiangNingLu', 3),
#         ('HanZhongLu', 1),
#         ('ZiRanBoWuGuan', 3),
#         ('NanJingXiLu', 2),
#         ('HuaiHaiZhongLu', 3),
#         ('XinTianDi', 2),
#         ('MaDangLu', 3),
#         ('ShiBoHuiBoWuGuan', 2),
#         ('ShiBoDaDao', 0)
#     ], # line 16
#     [
#         ('LongYangLu', 5),
#         ('HuaXiaZhongLu', 4),
#         ('LuoShanLu', 5),
#         ('ZhouPuDong', 4),
#         ('HeShaHangCheng', 4),
#         ('HangTouDong', 4),
#         ('XinChang', 5),
#         ('YeShengDongWuYuan', 5),
#         ('HuiNan', 6),
#         ('HuiNanDong', 9),
#         ('ShuYuan', 6),
#         ('LinGangDaDao', 4),
#         ('DiShuiHu', 0)
#     ]
# ]